/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.2.3).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.aks.openapi3.student.api;

import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.aks.openapi3.student.model.Student;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2020-08-23T21:34:41.819537+05:30[Asia/Kolkata]")

@Validated
@Api(value = "student", description = "the student API")
public interface StudentApi {

    default StudentApiDelegate getDelegate() {
        return new StudentApiDelegate() {};
    }

    /**
     * GET /student/{id} : Retrieves Student by ID
     *
     * @param id retrieves user by student id (required)
     * @return Retrieves Student by id (status code 200)
     */
    @ApiOperation(value = "Retrieves Student by ID", nickname = "getStudentById", notes = "", response = Student.class, tags={ "student", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Retrieves Student by id", response = Student.class) })
    @RequestMapping(value = "/student/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<Student> getStudentById(@ApiParam(value = "retrieves user by student id",required=true) @PathVariable("id") Long id) {
        return getDelegate().getStudentById(id);
    }

}
