openapi: 3.0.0
info:
   description: Codegen for student service
   version: 1.0.0
   title: Demo Service Specification
   contact:
      email: atulkumarsharma1986@gmail.com
tags:
-  name: student
   description: Student tag for demo purposes
servers:
-  url: http://localhost:8000/
   description: local host
paths:
   /student/{id}:
      get:
         tags:
         - student
         summary: Retrieves Student by ID
         operationId: getStudentById
         parameters:
         -  name: id
            in: path
            description: retrieves user by student id
            required: true
            schema:
               type: integer
               format: int64
         responses:
            200:
               description: Retrieves Student by id
               content:
                  application/json:
                     schema:
                        type: object
                        $ref: '#/components/schemas/Student'
components:
   schemas:
      Student:
         type: object
         required:
         - id
         - firstName
         - lastName
         - dateOfBirth
         - gender
         properties:
            id:
               type: integer
               format: int64
            firstName:
               type: string
               example: John
            lastName:
               type: string
               example: Smith
            dateOfBirth:
               type: string
               example: '1992-10-05'
            gender:
               type: string
               enum:
               - MALE
               - FEMALE
               - UNKNOWN